### ISSUE TITLE
Uncaught RuntimeError: The browser supports WebGL, but initialization failed.

### ISSUE THREAD

**Issue by FanisTGT** [webglearth/webglearth2#38]
Hello!

I detected an error.

Uncaught RuntimeError: The browser supports WebGL, but initialization failed.
Error
    at new t (https://www.webglearth.com/v2/api.js:14:14467)
    at new $ (https://www.webglearth.com/v2/api.js:40:4805)
    at new pt (https://www.webglearth.com/v2/api.js:48:13213)
    at new Y (https://www.webglearth.com/v2/api.js:127:482)
    at new <anonymous> (https://www.webglearth.com/v2/api.js:198:358)
    at initialize (https://www.prime-college.ru/globe-frame/:5:157)
    at onload (https://www.prime-college.ru/globe-frame/:14:118)

**Comment by klokan** [comment]
What browser in which version?
What hardware do you use?
If you try a different web browsers on the same hardware do you see the same error?
Have you seen the problem while visiting http://www.webglearth.com/ website?
The page: http://get.webgl.org/ tells you you have WebGL enabled?

**Comment by FanisTGT** [comment]
1. Google Chrome 40.0.2214.93 m (latest)
2. Win 7
3. Work in Mozilla Firefox
4. Yes. I have seen the same problem.
5. I see a cube. It rotates.

**Comment by petrsloup** [comment]
This seems to be a problem inside the Cesium itself. To be fixed by #44.
