### ISSUE TITLE
Uncaught RuntimeError

### ISSUE THREAD

**Issue by hunchang** [webglearth/webglearth2#96]
I use your plugin to develop a globe and also purchased the Maptiler for custom map.
However, not all the browser is running correctly, some having the following error:-

Uncaught RuntimeError: The browser supports WebGL, but initialization failed.
Error
at new t (https://www.webglearth.com/v2/api.js:428:16020)
at new H (https://www.webglearth.com/v2/api.js:462:31765)
at new Dt (https://www.webglearth.com/v2/api.js:473:4287)
at new Y (https://www.webglearth.com/v2/api.js:563:482)
at new (https://www.webglearth.com/v2/api.js:198:358)
at new <anonymous> (https://www.webglearth.com/v2/api.js:636:358)
at initialize (......

Tested with Windows Vista, chrome version (49.0.2623.112 m)
When visiting http://www.webglearth.com/ the globe is not appearing as well.
Visit - http://get.webgl.org/, saw the rotating cube.

Any idea to fix?

**Comment by obliquid** [comment]
same here. since a few days stopped working on chrome. firefox is working correctly.
