### ISSUE TITLE
Works on Microsoft Edge?

### ISSUE THREAD

**Issue by AnaBautistadeCabo** [webglearth/webglearth2#99]
I have tested WebGL Earth on Edge and it doesn't work. Edge has partial support for WebGL. The application doesn't  work because of these limitations ?

**Comment by oligoform** [comment]
it should, because https://cesiumjs.org works!

with webglearth2 i got errors in EDGE, too:
`SCRIPT5022: RuntimeError: The browser supports WebGL, but initialization failed.Error   at t (https://www.webglearth.com/v2/api.js:428:16014)   at H (https://www.webglearth.com/v2/api.js:462:31759)   at Dt (https://www.webglearth.com/v2/api.js:473:4281)   at Y (https://www.webglearth.com/v2/api.js:563:475)   at Anonymous function (https://www.webglearth.com/v2/api.js:636:356)   at initialize (https://mysite.com/:243:10)   at Anonymous function (https://mysite.com/:458:4)   at n.event.dispatch (https://mysite.com/wp-includes/js/jquery/jquery.js?ver=1.12.4:3:12312)   at r.handle (https://mysite.com/wp-includes/js/jquery/jquery.js?ver=1.12.4:3:9090)`

maybe @klokan have an idea?
